MAN/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'MAN.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^', include('orderSystem.urls', namespace='man')),

    url(r'^admin/', include(admin.site.urls)),
)

#This is to allow for dev envinronment to be able to serve files
if settings.DEBUG:
    urlpatterns += patterns('',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': settings.MEDIA_ROOT,
        }),
    )

orderSystem/urls.py
from django.conf.urls import patterns, include, url
from orderSystem import views

urlpatterns = patterns('',

    url(r'^$', views.UserAccountView, name='accountView'),
    url(r'^logout$', views.userLogoutView, name='logoutView'),

    #Homepage/Dashboard
    url(r'^home', views.index, name='home'),
    url(r'^account$', views.UserAccountView, name='accountView'),
    url(r'^account_bg$', views.UserAccount, name='account_bg'),

    url(r'^dashboard$', views.dashboardView, name='dashboardView'),
    url(r'^dashboard_gb$', views.dashboardView, name='dashboard_gb'),

    url(r'^profile$', views.profileView, name='profileView'),
    url(r'^profileSave$', views.profileSave, name='profileSave'),

    url(r'^staff$', views.staffView, name='staffView'),
    url(r'^staffSave$', views.staffSave, name='staffSave'),

    url(r'^client$', views.clientView, name='clientView'),
    url(r'^clientSave$', views.clientSave, name='clientSave'),
    url(r'^clientList$', views.clientList, name='clientList'),

    url(r'^orderform$', views.orderFormView, name='orderFormView'),
    url(r'^orderform(?P<order_id>[0-9]+)/$', views.orderFormView, name='orderFormView'),
    url(r'^order$', views.orderView, name='orderView'),
    url(r'^orderSave$', views.orderSave, name='orderSave'),


    url(r'^proforma$', views.proformaView, name='proformaView'),
    url(r'^proforma(?P<order_id>[0-9]+)/$', views.proformaView, name='proformaView'),
    url(r'^proformapdf$', views.proformaPDF, name='proformaPDF'),
    url(r'^proformapdf(?P<order_id>[0-9]+)/$', views.proformaPDF, name='proformaPDF'),

    url(r'^qsf$', views.qsfView, name='qsfView'),
    url(r'^qsf(?P<order_id>[0-9]+)/$', views.qsfView, name='qsfView'),
    url(r'^qsfpdf$', views.qsfPDF, name='qsfPDF'),
    url(r'^qsfpdf(?P<order_id>[0-9]+)/$', views.qsfPDF, name='qsfPDF'),

    url(r'^calculation$', views.calculationView, name='calculationView'),
    url(r'^calculation(?P<order_id>[0-9]+)/$', views.calculationView, name='calculationView'),

    url(r'^mof$', views.mofView, name='mofView'),
    url(r'^mof(?P<order_id>[0-9]+)/$', views.mofView, name='mofView'),
    url(r'^mofpdf$', views.mofPDF, name='mofPDF'),
    url(r'^mofpdf(?P<order_id>[0-9]+)/$', views.mofPDF, name='mofPDF'),


)

orderSystem/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse, HttpResponseServerError
from django.contrib.auth import authenticate, login, logout

from django.shortcuts import render, redirect
from django.http import HttpResponse
from orderSystem.models import Employee, User, Client, Country, DeliveryTime, SpecialDiscount, Discount, Currency, DutyType, TruckAge, PaymentTerm, Order, CustomConfiguration, Depreciation, CustomsRate
from django.db.models import Count, Min, Sum, Avg, Max
from django.template import RequestContext, loader
from django.views.generic import ListView
from django.http import HttpResponseRedirect, HttpResponse, HttpResponseServerError
from datetime import date, datetime, timedelta
from django.contrib.auth import authenticate, login, logout
from django.core.urlresolvers import reverse
from xlwt import Workbook, easyxf
# from django.contrib.auth.models import User
from validate_email import validate_email
from django.db.models import Count, Q
from django.contrib.auth.hashers import make_password
from django.views.decorators.csrf import csrf_exempt, csrf_protect
from django.conf import settings
import re, operator
import calendar
from django.db import transaction
from reportlab.pdfgen import canvas
import time
from datetime import date, datetime

import json
import StringIO
import cStringIO as StringIO
import ho.pisa as pisa
from django.template.loader import get_template
from django.template import Context
from django.http import HttpResponse
from cgi import escape

permissions = {'Administrator' : 32, 'Sales Representative' : 16}



def render_to_pdf(template_src, context_dict):
    template = get_template(template_src)
    context = Context(context_dict)
    html  = template.render(context)
    result = StringIO.StringIO()

    pdf = pisa.pisaDocument(StringIO.StringIO(html.encode("utf-8")), result)
    if not pdf.err:
        return HttpResponse(result.getvalue(), mimetype='application/pdf')
    return HttpResponse('We had some errors<pre>%s</pre>' % escape(html))

def fetch_resources(uri, rel):
    import os.path
    from django.conf import settings

    path = os.path.join(
            settings.STATIC_ROOT,
            uri.replace(settings.STATIC_URL, ""))
    return path

def render_to_pdf2(template_src, context_dict):
    """Function to render html template into a pdf file"""
    template = get_template(template_src)
    context = Context(context_dict)
    html  = template.render(context)
    result = StringIO.StringIO()

    pdf = pisa.pisaDocument(StringIO.StringIO(html.encode("UTF-8")),
                                            dest=result,
                                            encoding='UTF-8',
                                            link_callback=fetch_resources)
    if not pdf.err:
        response = HttpResponse(result.getvalue(), mimetype='application/pdf')

        return response

    return HttpResponse('We had some errors<pre>%s</pre>' % escape(html))



def index(request):
    return render(request, 'index.html', {})

def dashboardView(request):
    context = {}
    ckwargs = {}
    pkwargs = {}
    skwargs = {}

    if request.user.is_authenticated():

        return render(request, 'dashboard.html', context)
    else:
        return render(request, 'login.html', context)

def userLogoutView(request):
    logout(request)
    return render(request, 'login.html', {})

def UserAccountView(request):
    context = {}
    if request.user.is_authenticated():
        return userLogoutView(request)
    else:
        return render(request, 'login.html', context)

def UserAccount(request):

    if request.POST and not request.user.is_authenticated():
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            if not hasattr(user, 'employee'):
                response_data = {'is_valid':False, 'data':'User account improperly setup. Contact sys Admin'}
                return HttpResponse(json.dumps(response_data), mimetype="application/json")

            if user.is_active:
                login(request, user)
                redirect_url = reverse('man:dashboardView')

                response_data = {'is_valid':True, 'data':'success', 'redirect_url': redirect_url}
                return HttpResponse(json.dumps(response_data), mimetype="application/json")
                # Redirect to a success page.
            else:
                # Return a 'disabled account' error message
                response_data = {'is_valid':False, 'data':'Account has been Disabled'}
                return HttpResponse(json.dumps(response_data), mimetype="application/json")
        else:
            # Return an 'invalid login' error message.
            response_data = {'is_valid':False, 'data':'Invalid Login details'}
            return HttpResponse(json.dumps(response_data), mimetype="application/json")
    else:
        # Return an 'invalid login' error message.
        response_data = {'is_valid' : False, 'data':'Post parameters not available'}
        return HttpResponse(json.dumps(response_data), mimetype="application/json")

@transaction.atomic
def profileSave(request):

    if request.POST and request.user.is_authenticated():
        is_valid = False
        avatar_url = False
        message = "success"

        if request.POST['edit-type'] == 'info':
            if ( request.POST['profile_email']):
                is_email_valid = validate_email(request.POST['profile_email'])
            if not (request.POST['profile_username']):
                message = "Fill in username"
            if ( not (request.POST['profile_firstname']) or not request.POST['profile_lastname']):
                message = "Fill in First name and Last name"
            elif ( not (request.POST['profile_phone']) or not request.POST['profile_phone'].isdigit()):
                message = "Mobile number invalid"
            elif ( request.POST['profile_email'] and not is_email_valid):
                message = "Please provide a valid email address"
            elif not ('profile_phone' in request.POST) or not validPhoneNumber(request.POST['profile_phone']):
                message = "Mobile number invalid. should be of the format 23324XXXXXXX"

            # Check if customer username already exists
            if(request.user.username != request.POST['profile_username']):
                user = User.objects.all().filter(username = request.POST['profile_username'])
                if(user):
                    message = "Username already exists. Please Try another name"

            # Check if phone number already exists
            if(not hasattr(request.user, 'employee') or request.user.employee.phone_number != request.POST['profile_phone']):
                user_phone = Employee.objects.all().filter(phone_number = request.POST['profile_phone'], status='A')
                if(user_phone):
                    message = "Phone number already in user by another employee"

            if(message == "success"):
                user = User.objects.get(pk=request.user.id)
                user.username = request.POST['profile_username']
                user.first_name = request.POST['profile_firstname']
                user.last_name = request.POST['profile_lastname']
                user.email = request.POST['profile_email']
                user.save()

                if(user):
                    if(hasattr(user, 'employee') and user.employee):
                        user.employee.phone_number = request.POST['profile_phone']
                        # user.employee.gender = request.POST['profile_gender']
                        user.employee.save()
                        employee = user.employee
                    else:
                        employee = Employee.objects.create(phone_number=request.POST['profile_phone'], user=user)

                    if employee:
                        message = "<b>Congratulations!</b> Profile has been updated successfully"
                        is_valid = True
                else:
                    message = "Could not update profile information. Please check with system admin"
                    message = "<b>Oops..</b>" + message
            else:
                message = "<b>Oops..</b>" + message

        if request.POST['edit-type'] == 'password':
            if ( not request.POST['profile_password'] or  not request.POST['profile_new_passord'] or  not request.POST['profile_confirm_password']):
                message = "Please provide a the Old, New and Confirmation password"
            elif not request.user.check_password(request.POST['profile_password']):
            #now check to see if the old password is correct
                message = "Existing password is incorrect"
                message = "<b>Oops..</b>" + message
            elif (request.POST['profile_new_passord'] != request.POST['profile_confirm_password']):
                message = "New password and Confirmation passwords do not match"
            else:
                user = User.objects.get(pk=request.user.id)
                if(user):
                    user.set_password(request.POST['profile_new_passord'])
                    user.save()
                    message = "<b>Congratulations!</b> password has been updated successfully"
                    is_valid = True
                else:
                    message = "<b>Congratulations!</b> password has been updated successfully"
                    message = "<b>Oops..</b>" + message

        if 'upload_avatar' in request.FILES:
            upload_avatar = request.FILES['upload_avatar']
            user = User.objects.get(pk=request.user.id)
            if(hasattr(user, 'employee') and user.employee):
                user.employee.avatar.save(upload_avatar.name,upload_avatar)
                avatar_url = user.employee.avatar.url

orderSystem/templates/login.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
  <meta name="description" content="">
  <meta name="author" content="">
  <link rel="shortcut icon" href="{% static 'images/favicon.png' %}" type="image/png">

  <title>MAN Truck Sales/Ordering System</title>

  <link href="{% static 'css/style.default.css' %}" rel="stylesheet">

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
  <script src="{% static 'js/html5shiv.js'%}"></script>
  <script src="{% static 'js/respond.min.js'%}"></script>
  <![endif]-->
</head>

<body class="signin">

<!-- Preloader -->
<div id="preloader">
    <div id="status"><i class="fa fa-spinner fa-spin"></i></div>
</div>

<section>
  
    <div class="signinpanel">
        
        <div class="row">
            
            <div class="col-md-7">
                
                <div class="signin-info">
                    <div class="logopanel">
                        <h1><span>[</span> MBG Limited <span>]</span></h1>
                    </div><!-- logopanel -->
                
                    <div class="mb20"></div>
                
                    <h5><strong>Welcome MBG Truck Ordering System</strong></h5>
                    <ul>
                        <li><i class="fa fa-arrow-circle-o-right mr5"></i> Enter Customer requests</li>
                        <li><i class="fa fa-arrow-circle-o-right mr5"></i> Generate Proforma Invoice</li>
                        <li><i class="fa fa-arrow-circle-o-right mr5"></i> Generate QSF </li>
                        <li><i class="fa fa-arrow-circle-o-right mr5"></i> Generate Calculation Sheets</li>
                        <li><i class="fa fa-arrow-circle-o-right mr5"></i> and much more...</li>
                    </ul>
                    <div class="mb20"></div>
                    <strong>No account? <a href="signup.html">Contact Administrator</a></strong>
                </div><!-- signin0-info -->
            
            </div><!-- col-sm-7 -->
            
            <div class="col-md-5">
                
                <form id="login_form" action="{% url 'man:account_bg' %}" class="login-form-signin" method="post">
                    {% csrf_token %}
                    <h4 class="nomargin">Sign In</h4>
                    <p class="mt5 mb20">Login to access your the system.</p>
                
                    <input name="username" type="text" class="form-control uname" placeholder="Username" />
                    <input name="password" type="password" class="form-control pword" placeholder="Password" />
                    <a href=""><small>Forgot Your Password?</small></a>
                    <button type="submit"  class="btn btn-success btn-block">Sign In</button>
                </form>
            </div><!-- col-sm-5 -->
            
        </div><!-- row -->
        
        <div class="signup-footer">
            <div class="pull-left">
                &copy; 2014. All Rights Reserved. MBG ltd
            </div>
            <div class="pull-right">
                Created By: <a href="#" target="_blank">Diluo Company Limited</a>
            </div>
        </div>
        
    </div><!-- signin -->
  
</section>

<script>
{# alert("page loaded");#}
{#    $('#login_form').submit(function(e) {#}
{#        alert('click');#}
{#        e.preventDefault();#}
{#        $.ajax({ // create an AJAX call...#}
{#            data: $(this).serialize(), // get the form data#}
{#            type: $(this).attr('method'), // GET or POST#}
{#            url: $(this).attr('action'), // the file to call#}
{#            success: function(response) { // on success..#}
{##}
{#                if(response.is_valid == true){#}
{#                    window.location.href = response.redirect_url;#}
{##}
{#                }else{#}
{#                    $('#error_div').html(response.data);#}
{#                    $('#error_div').fadeIn(700);#}
{#                    $('#error_div').fadeOut(15000);#}
{##}
{#                }#}
{##}
{##}
{#            },#}
{#            error: function(e, x, r) { // on error..#}
{#                alert("error");#}
{#                $('#error_div').html(e);#}
{#            }#}
{#        });#}
{#     });#}

</script>
{#<script type="text/javascript" src="{% static 'js/site-custom.js' %}"></script>#}
<script src="{% static 'js/jquery-1.10.2.min.js'%}"></script>
{#<script src="{% static 'js/jquery-migrate-1.2.1.min.js'%}"></script>#}
{#<script src="{% static 'js/bootstrap.min.js'%}"></script>#}
{#<script src="{% static 'js/modernizr.min.js'%}"></script>#}
{#<script src="{% static 'js/retina.min.js'%}"></script>#}

<script src="{% static 'js/custom.js'%}"></script>

</body>
</html>

orderSystem/templates/proforma.html
{% extends "base.html" %}
{% load staticfiles %}

{% block extra_css %} {% endblock %}

{% block pageName %}
    <i class="fa fa-home"></i> Proforma
{% endblock %}

{% block pageSubs %}
    Order proforma template
{% endblock %}

{% block pageNav %}
    proforma
{% endblock %}

{% block pageContent %}


    <div class="col-sm-9">
        <p class="mb20"><a href="{% url 'man:proformaPDF' %}?order_id={{  order.id }}">Click Here</a> to get a printable version of this proforma</p>

        <div class="panel panel-default">
            <div class="panel-heading">
                <img src="{% static 'images/MBG/header.jpg' %}"  width="800" alt=""/>
            </div>
            <!-- panel-body -->
            <div class="panel-body">
                <div class="row">
                    <span class="col-md-4">Email: {{ creator.email }}</span>
                    <span class="col-md-4">Tel: {{ creator.employee.phone_number }}</span>
                    <span class="col-md-4">Date: {{ calculated.DATE }}</span>
                </div>


                <div class="row">


                    <div class="col-md-12">
                        <br/>
                        <br/>
                        <b>
                        {{ order.client.company_name }}<br/>
                        Att: {{ order.client.contact_person }}<br/>
                        {{ order.client.address }}<br/>
                        {{ order.client.city }} - {{ order.client.country.name }}<br/>
                        Email: {{ order.client.email }}<br/>
                        </b>
                        <br/>
                        <br/>

                        <b>PROFORMA INVOICE NO: {{ order.order_number }} {{ order.order_truck_subscr }} {{ order.gfz_number }} </b><br/><br/>
                        We refer to your inquiry and are pleased to quote, based on our general terms and conditions of
                        delivery and sale as follows:
                        <br/>
                        <br/>
                         {{ order.man_truck_model }} {{ order.gfz_number }} <br/>
                         {{ order.order_truck_subscr }}<br/><br/>
                        <b>
                            <div>
                                <span>Offer price for 1 Unit, {{ order.duty_type.name }}</span>
                                <span class="pull-right"> $450000*** &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</span><br/><br/>
                            </div>
                            <div>

                                <span>Offer price for {{ order.quantity }} Unit{% if order.quantity > 1 %}s{% endif %},  {{ order.duty_type.name }}</span>
                                <span class="pull-right"> $450000 &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</span><br/>
                            </div>
                        </b>
                        <br/>
                        <br/>

                    </div>

                    <div class="col-md-12">

                        <p><b>Prices:</b></p>

                        <p>Are net, in EURO and acc. to Incoterms, edition 2010.</p>
                        <br/>

                        <p><b>Delivery:</b></p>

                        <p>{{ order.estimated_delivery_time.name }} from receipt of firm order.</p>
                        `


                        <br/>

                        <p><b>Payment:</b></p>
                        100% out of an irrevocable letter of credit confirmed by a first class European Bank or by Bank Transfer.<br/>
                        All charges to debit of applicant .

                        <br/>
                        <br/>
                        <p><b>Guarantee:</b></p>
                        12 months unlimited mileage, or expiring 18 months after B/L date at the latest.<br/>
                        24 months or 200.000 km, or expiring 30 months after B/L date whatever comes first,<br/>
                        on the drive train (engine, gearbox, driven axles) only.

                        <br/><br/>
                        <p><b>NOTE: During the warranty period all servicing should be done by an authorized MAN dealer</b></p>
                        <br/><br/>

                        <p><b>Validity:</b></p>

                        <p>Valid till: {{ calculated.VALID }}</p>

                        <p>Yours Sincerely,</p>

                        <br/>

                        <span class="thumb"><img height="60px" src="{{ creator.employee.signature.url }}" alt=""/></span>
                        <span class="thumb"><img src="{% static 'images/MBG/stamp.png' %}" alt=""/></span>


                        <br/>

                        <p>{{ creator.first_name }} {{ creator.last_name }}</p>

                        <p>{{ creator.role }}</p>

                    </div>
                </div>

            </div>
            <!-- panel-body -->
            <div class="panel-footer">
                <img src="{% static 'images/MBG/footer.jpg' %}" width="800" alt=""/>
            </div>
            <!-- panel-footer -->
        </div>
        <!-- panel -->
    </div><!-- col-sm-6 -->

    </div><!-- row -->



{% endblock %}

{% block extra_js %} {% endblock %}

orderSystem/templates/proformaPDF.html
{% load staticfiles %}

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
    <head>
        <title>My Title</title>
        <style type="text/css">

            .higlightcell{
                background-color: #f7ecb5;
            }
        </style>
    </head>
    <body>

    <div class="col-sm-9">

        <div class="panel panel-default">
            <div class="panel-heading">
                <img src="{% static 'images/MBG/header.jpg' %}" alt=""/>
{#                <img src="{% static 'images/MBG/proforma_header.png' %}" width="800" height="150" alt=""/>#}
            </div>
            <!-- panel-body -->
            <div class="panel-body">
            <table>
                <tr>
                    <td>Email: {{ creator.email }}</td>
                    <td>Tel: {{ creator.employee.phone_number }}</td>
                    <td>Date: {{ calculated.DATE }}</td>
                </tr>
            </table>
                <div class="row">

                    <div class="col-md-12">
                        <br/>
                        <br/>
                        <b>
                        {{ order.client.company_name }}<br/>
                        Att: {{ order.client.contact_person }}<br/>
                        {{ order.client.address }}<br/>
                        {{ order.client.city }} - {{ order.client.country.name }}<br/>
                        Email: {{ order.client.email }}<br/>
                        </b>
                        <br/>
                        <br/>

                        <b>PROFORMA INVOICE NO: {{ order.order_number }} {{ order.order_truck_subscr }} {{ order.gfz_number }} </b><br/><br/>
                        We refer to your inquiry and are pleased to quote, based on our general terms and conditions of
                        delivery and sale as follows:
                        <br/>
                        <br/>
                         {{ order.man_truck_model }} {{ order.gfz_number }} <br/>
                         {{ order.order_truck_subscr }}<br/><br/>
                        <b>

                        <table>
                            <tr>
                                <td>Offer price for 1 Unit, {{ order.duty_type.name }}</td>
                                <td align="right">{{ order.currency.symbol }}{{ calculated.SALE_PRICE }}&nbsp&nbsp&nbsp&nbsp&nbsp</td>
                            </tr>
                        </table>
                        <table>
                            <tr>
                                <td>Offer price for {{ order.quantity }} Unit{% if order.quantity > 1 %}s{% endif %},  {{ order.duty_type.name }}</td>
                                <td align="right">{{ order.currency.symbol }}{{ calculated.SALE_PRICE_TOTAL }}&nbsp&nbsp&nbsp&nbsp&nbsp</td>
                            </tr>
                            <tr><td style="border-bottom: 1px">&nbsp&nbsp&nbsp&nbsp&nbsp</td></tr>
                        </table>
                        </b>
                    </div>

                    <div class="col-md-12">

                        <b><u>Prices:</u></b><br/>

                        Are net, in EURO and acc. to Incoterms, edition 2010.

                        <br/><br/><b><u>Delivery:</u></b><br/>
                        {{ order.estimated_delivery_time.name }} from receipt of firm order.
                        `
                        <br/><br/><b><u>Payment:</u></b><br/>
                        100% out of an irrevocable letter of credit confirmed by a first class European Bank or by Bank Transfer.<br/>
                        All charges to debit of applicant .

                        <br/><br/><b><u>Guarantee:</u></b><br/>
                        12 months unlimited mileage, or expiring 18 months after B/L date at the latest.<br/>
                        24 months or 200.000 km, or expiring 30 months after B/L date whatever comes first,<br/>
                        on the drive train (engine, gearbox, driven axles) only.

                        <br/>
                        <p><b><u>NOTE: During the warranty period all servicing should be done by an authorized MAN dealer</u></b></p>

                        <br/><br/><b>Validity:</b><br/>
                        Valid till: {{ calculated.VALID }}

                        <br/><br/>Yours Sincerely,<br/>

                        <span class="thumb"><img height="60px" src="{{ path }}{{ creator.employee.signature.url }}" alt=""/></span>
                        <span class="thumb"><img height="120px" src="{% static 'images/MBG/stamp.png' %}" alt=""/></span>


                        <br/>

                        <p>{{ creator.first_name }} {{ creator.last_name }}</p>

                        <p>{{ creator.role }}</p><br/>

                    </div>
                </div>

            </div>
            <!-- panel-body -->
            <div class="panel-footer">
                <img src="{% static 'images/MBG/footer.jpg' %}" alt=""/>
            </div>
            <!-- panel-footer -->
        </div>
        <!-- panel -->
    </div><!-- col-sm-6 -->

    </div><!-- row -->



    </body>
</html>